name: Terraform deployment for VPC
on:
  push:
    paths:
      - 'ec2_launch/**'
jobs:
  terraform-deployment:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::247548036690:role/github-actions-oidc
        aws-region: "eu-central-1"
        

    - name: Clone/Checkout your repository code
      uses: actions/checkout@v2

    - name: Terraform setup
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      working-directory: ec2_launch/
      run: terraform init

    - name: Terraform Plan
      run: terrafrom plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
